Drop testing dolfinx-0.9 in ci_unversioned_only.yml, because of installation failure with
  scikit_build_core._vendor.pyproject_metadata.ConfigurationError: Field "project.license" has an invalid type, expecting a dictionary of strings (got "LGPL-3.0-or-later")

when trying to determine if the newer RBniCSx 0.1.1 is compatible (and it will not be).

RBniCSx 0.1.0 is still test with dolfinx 0.9 in the ci.yml file, with explicit RBniCSx versioning